### PR TITLE
Java 17, skull bug fix and code refactoring

### PR DESCRIPTION
**Pull request by ChimpGamer**
I also wanted to get rid of XMaterial and XSound since they aren't useful anymore with the minimum version requirement of 1.19 but didn't have to time for it.

### CODE REVIEW

**Comment by ItzSave** [comment]
This is a very extensive change list have you done any testing?

**Comment by ChimpGamer** [comment]
Yea I tested it and found no issue.

**Comment by ChimpGamer** [comment]
I found some time to get rid of XSound and XMaterial. I also tested these changes and found no issues..

**Review by ItzSave — COMMENTED** [review]
Was there any reasons for getting rid of the XSound & XMaterial classes?

**Comment by ChimpGamer** [comment]
Since the minimum api version is 1.19 there is no reason to use them.

**Comment by giantfurkii** [comment]
When I install the Deluxe coin flip plugin, it is duped with zauctionhouse.

**Pull request merged**
